/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

import type { OnEvent, PromiseOrValue, TypedEvent, TypedEventFilter, TypedListener } from "../../common";

export interface SafePRBMathTesterInterface extends utils.Interface {
  functions: {
    "avg(uint256,uint256)": FunctionFragment;
    "ceil(uint256)": FunctionFragment;
    "div(uint256,uint256)": FunctionFragment;
    "e()": FunctionFragment;
    "exp(uint256)": FunctionFragment;
    "exp2(uint256)": FunctionFragment;
    "floor(uint256)": FunctionFragment;
    "frac(uint256)": FunctionFragment;
    "fromUint(uint256)": FunctionFragment;
    "gm(uint256,uint256)": FunctionFragment;
    "inv(uint256)": FunctionFragment;
    "ln(uint256)": FunctionFragment;
    "log10(uint256)": FunctionFragment;
    "log2(uint256)": FunctionFragment;
    "mul(uint256,uint256)": FunctionFragment;
    "pi()": FunctionFragment;
    "pow(uint256,uint256)": FunctionFragment;
    "powu(uint256,uint256)": FunctionFragment;
    "scale()": FunctionFragment;
    "sqrt(uint256)": FunctionFragment;
    "toUint(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "avg"
      | "ceil"
      | "div"
      | "e"
      | "exp"
      | "exp2"
      | "floor"
      | "frac"
      | "fromUint"
      | "gm"
      | "inv"
      | "ln"
      | "log10"
      | "log2"
      | "mul"
      | "pi"
      | "pow"
      | "powu"
      | "scale"
      | "sqrt"
      | "toUint",
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "avg",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: "ceil", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: "div",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: "e", values?: undefined): string;
  encodeFunctionData(functionFragment: "exp", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "exp2", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "floor", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "frac", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "fromUint", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: "gm",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: "inv", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "ln", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "log10", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "log2", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: "mul",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: "pi", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pow",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: "powu",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: "scale", values?: undefined): string;
  encodeFunctionData(functionFragment: "sqrt", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "toUint", values: [PromiseOrValue<BigNumberish>]): string;

  decodeFunctionResult(functionFragment: "avg", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ceil", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "div", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "e", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exp2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "floor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "frac", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fromUint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "inv", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ln", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "log10", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "log2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pi", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "powu", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "scale", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sqrt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "toUint", data: BytesLike): Result;

  events: {};
}

export interface SafePRBMathTester extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SafePRBMathTesterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    avg(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber] & { result: BigNumber }>;

    ceil(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    div(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber] & { result: BigNumber }>;

    e(overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    exp(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    exp2(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    floor(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    frac(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    fromUint(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    gm(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber] & { result: BigNumber }>;

    inv(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    ln(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    log10(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    log2(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    mul(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber] & { result: BigNumber }>;

    pi(overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    pow(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber] & { result: BigNumber }>;

    powu(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber] & { result: BigNumber }>;

    scale(overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    sqrt(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;

    toUint(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber] & { result: BigNumber }>;
  };

  avg(x: PromiseOrValue<BigNumberish>, y: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  ceil(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  div(x: PromiseOrValue<BigNumberish>, y: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  e(overrides?: CallOverrides): Promise<BigNumber>;

  exp(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  exp2(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  floor(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  frac(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  fromUint(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  gm(x: PromiseOrValue<BigNumberish>, y: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  inv(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  ln(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  log10(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  log2(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  mul(x: PromiseOrValue<BigNumberish>, y: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  pi(overrides?: CallOverrides): Promise<BigNumber>;

  pow(x: PromiseOrValue<BigNumberish>, y: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  powu(x: PromiseOrValue<BigNumberish>, y: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  scale(overrides?: CallOverrides): Promise<BigNumber>;

  sqrt(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  toUint(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    avg(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    ceil(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    div(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    e(overrides?: CallOverrides): Promise<BigNumber>;

    exp(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    exp2(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    floor(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    frac(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    fromUint(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    gm(x: PromiseOrValue<BigNumberish>, y: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    inv(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    ln(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    log10(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    log2(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    mul(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    pi(overrides?: CallOverrides): Promise<BigNumber>;

    pow(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    powu(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    scale(overrides?: CallOverrides): Promise<BigNumber>;

    sqrt(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    toUint(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    avg(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    ceil(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    div(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    e(overrides?: CallOverrides): Promise<BigNumber>;

    exp(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    exp2(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    floor(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    frac(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    fromUint(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    gm(x: PromiseOrValue<BigNumberish>, y: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    inv(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    ln(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    log10(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    log2(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    mul(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    pi(overrides?: CallOverrides): Promise<BigNumber>;

    pow(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    powu(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    scale(overrides?: CallOverrides): Promise<BigNumber>;

    sqrt(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    toUint(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    avg(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    ceil(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    div(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    e(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    exp(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    exp2(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    floor(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    frac(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fromUint(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gm(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    inv(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ln(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    log10(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    log2(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mul(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    pi(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pow(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    powu(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    scale(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sqrt(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    toUint(x: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
