/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFErc20__factory } from "./IFErc20__factory";
export { IInterestRateModel__factory } from "./IInterestRateModel__factory";
export { IPriceOracle__factory } from "./IPriceOracle__factory";
export { IRiskManager__factory } from "./IRiskManager__factory";
export { ITokenBase__factory } from "./ITokenBase__factory";
