/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFErc20 } from "./IFErc20";
export type { IInterestRateModel } from "./IInterestRateModel";
export type { IPriceOracle } from "./IPriceOracle";
export type { IRiskManager } from "./IRiskManager";
export type { ITokenBase } from "./ITokenBase";
